export {Character} from './page/Character'
export {Consume} from './page/Consume'
export {Create} from './page/Create'
export {Credits} from './page/Credits'
export {Hi} from './page/Hi'
export {NotFound} from './page/NotFound'
export {Resume} from './page/Resume'
export {Story} from './page/Story'
