export {Formal} from "./page/Professional/Formal"
export {Informal} from "./page/Professional/Informal"
export {Bio} from "./page/Personal/Bio"
export {TrueMeaning} from "./page/Personal/TrueMeaning"
export {Hobby} from "./page/Personal/Hobby"
export {NotFound} from "./page/NotFound"
