export {Formal} from "./page/Formal"
export {Informal} from "./page/Informal"
export {Bio} from "./page/Bio"
export {TrueMeaning} from "./page/TrueMeaning"
export {Hobby} from "./page/Hobby"
export {NotFound} from "./page/NotFound"
