export {Background} from './component/Background'
export {Canvas} from './component/Canvas'
export {mkWaves, mkWavePhysics, storeWavePhysics} from './component/Canvas/wave'
export {Contact} from './component/Contact'
export {Content} from './component/Content'
export {NavMain} from './component/NavMain'
export {NavSubMobile} from './component/NavSubMobile'
export {NavSubTube} from './component/NavSubTube'
export {Sidebar} from './component/Sidebar'
export {Title} from './component/Title'

export type {WaveConfigs} from './component/Canvas/wave'
